### ISSUE TITLE
Question: Annotation Info

### ISSUE THREAD

**Issue by LiNk-NY** [rargelaguet/scnmt_gastrulation#1]
Hi Ricard, @rargelaguet 
CC: Al @ajabadi
Thank you for making this data available to the SC research community. 
This is a great resource for advancing the multi-modal analysis of single cell
data. 

I would like to be able to reproduce the summarization of methylated regions.
I see the code for doing so under [load_data.R](https://github.com/rargelaguet/scnmt_gastrulation/blob/master/metacc/pseudobulk_profiles/load_data.R) and [load_annotations.R](https://github.com/rargelaguet/scnmt_gastrulation/blob/master/metacc/pseudobulk_profiles/load_annotations.R) but I am not sure where the annotation datasets are coming from. 
They look like these below. Are these publicly available somewhere? 

```
# IMPORTANT: For every CpG/GpC site, the the rate must be 0 or 1

# (2) genomic feature annotation files in BED6 format
#   chr start end strand id anno
#   1	3531624	3531843	*	CGI_1	CGI
#   1	3670619	3671074	*	CGI_2	CGI
#   1	3671654	3672156	*	CGI_3	CGI
```

Thank you for your help. 
With your permission (and attribution of course), we would like to distribute the data as an `ExperimentHub` package in Bioconductor. 

Best regards,
Marcel

**Comment by rargelaguet** [comment]
Hi Marcel,
I am sorry for the slow reply.
The genomic context annotations can be downloaded with the [parsed data set](http://ftp.ebi.ac.uk/pub/databases/scnmt_gastrulation). They are in `.../features/genomic_contexts.` In that folder there is also a README file which explains where do the annotations come from. 

Happy for this to be distributed as an `ExpertimentHub`, thanks!

**Comment by jonathangriffiths** [comment]
Hi @LiNk-NY 

Sorry to jump in here, but do you know how this is going? I was thinking about incorporating this dataset into our existing MouseGastrulationData package (https://bioconductor.org/packages/release/data/experiment/html/MouseGastrulationData.html) alongside another ATAC-seq dataset that was recently released. However, we shouldn't be duplicating data on ExperimentHub - so if you're nearly there, then I can leave it to you. Alternatively, we might be able to merge your work into MGD via pull request, if you are interested.

Thanks,
Jonny

**Comment by LiNk-NY** [comment]
Hi Jonny, @jonathangriffiths 
We already have the package submitted to Bioconductor. See: https://github.com/Bioconductor/Contributions/issues/1470

**Comment by LiNk-NY** [comment]
Hi Ricard, @rargelaguet 

I was able to post the `MultiAssayExperiment` object on `ExperimentHub` see the issue posted above to follow progress, if interested. 

OTOH, when trying to reproduce the summaries, the link you provided does not work for me. I don't see `../features/genomic_contexts` at that link or in the tarballs.
Perhaps there is an admin layer that doesn't allow access?
Thank you for your help.

**Comment by jonathangriffiths** [comment]
Super, I'll make sure to point people towards your package

Jonny

**Comment by aljabadi** [comment]
Hi @LiNk-NY,

Here is the link to my copy of the `.bed` files in `gastrulation/features/filt`.

https://cloudstor.aarnet.edu.au/plus/s/B2fZNpBErhepXOz

Hope it helps

Al

**Comment by LiNk-NY** [comment]
Thanks Al! @ajabadi
