### ISSUE TITLE
unable to find an inherited method for function ‘exprs’ for signature ‘"SingleCellExperiment"’

### ISSUE THREAD

**Issue by Van1yu3** [rargelaguet/scnmt_gastrulation#2]
Hi!

When I tried reproducing your result on the MOFA method, I got an error which I failed to deal with.

More specifically, I failed to use `exprs()` function on the `SingleCellExperiment` class, and got the following error message when I ran the code [here](https://github.com/rargelaguet/scnmt_gastrulation/blob/642c14a14fa0a88b708d357ae6daaf3eae480a23/metaccrna/mofa/E7.5/load_data.R#L56):

> Error in (function (classes, fdef, mtable)  :
>  unable to find an inherited method for function ‘exprs’ for signature ‘"SingleCellExperiment"’

My `sessionInfo()` is as follows:

> R version 3.5.3 (2019-03-11)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS: /home/user/software/R-353/lib64/R/lib/libRblas.so
> LAPACK: /home/user/software/R-353/lib64/R/lib/libRlapack.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
> 
> attached base packages:
> [1] parallel  stats4    stats     graphics  grDevices utils     datasets
> [8] methods   base
> 
> other attached packages:
>  [1] SingleCellExperiment_1.4.1  SummarizedExperiment_1.12.0
>  [3] DelayedArray_0.8.0          BiocParallel_1.16.6
>  [5] matrixStats_0.56.0          Biobase_2.42.0
>  [7] GenomicRanges_1.34.0        GenomeInfoDb_1.18.2
>  [9] IRanges_2.16.0              S4Vectors_0.20.1
> [11] BiocGenerics_0.28.0         purrr_0.3.3
> [13] data.table_1.12.8
> 
> loaded via a namespace (and not attached):
>  [1] lattice_0.20-38        bitops_1.0-6           grid_3.5.3
>  [4] magrittr_1.5           zlibbioc_1.28.0        rlang_0.4.5
>  [7] XVector_0.22.0         Matrix_1.2-15          tools_3.5.3
> [10] RCurl_1.98-1.1         compiler_3.5.3         GenomeInfoDbData_1.2.0
> 

I wonder if it's my own problem? 

Thanks a lot!

**Comment by rargelaguet** [comment]
Hi, I think is because of an update in SingleCellExperiment where `expr(sce)` has been replaced by `logcounts(sce)`. Can you check?

**Comment by Van1yu3** [comment]
When I replaced `exprs` by `logcounts`, the error no more occurred. However, I did not see any updating message about this `exprs` function on either the [reference manual](https://www.bioconductor.org/packages/release/bioc/manuals/SingleCellExperiment/man/SingleCellExperiment.pdf) or the [news](https://www.bioconductor.org/packages/release/bioc/news/SingleCellExperiment/NEWS) in this SingleCellExperiment package. May I ask how you know about that?

**Comment by rargelaguet** [comment]
The reason I found out is the same as you :) After updating the packages, `expr(sce)` stopped working and when checking the last vignettes I noticed they used `logcounts(sce)` instead. I will update the scripts in the repository. Thanks for reporting!

**Comment by Van1yu3** [comment]
Thanks a lot for your instant reply! Then this issue can be closed.
