### ISSUE TITLE
questions about variable names

### ISSUE THREAD

**Issue by yuhanH** [rargelaguet/scnmt_gastrulation#3]
HI, Ricard @rargelaguet 
I am wondering what variables in the Methylation data represent. 
Rate seems to represent the beta value  for the aggregated regions.  What the meaning of `Nmet` and `N`? Can I use `N` and `Nmet` to obtain `rate`?
```
             id_met                 id           anno Nmet N rate
1: E7.5_Plate12_H02 ENSMUSG00000000001 prom_2000_2000    0 4    0
2: E7.5_Plate12_H02 ENSMUSG00000000049 prom_2000_2000    0 5    0
3: E7.5_Plate12_H02 ENSMUSG00000000085 prom_2000_2000    0 3    0
4: E7.5_Plate12_H02 ENSMUSG00000000120 prom_2000_2000    1 7   14
5: E7.5_Plate12_H02 ENSMUSG00000000126 prom_2000_2000    0 5    0
6: E7.5_Plate12_H02 ENSMUSG00000000148 prom_2000_2000    0 7    0
```
Thanks for your help!

**Comment by rargelaguet** [comment]
Hi Yuhan,
`Nmet` is the number of methylated CpGs within that cell and genomic region, and `N` is the total number of CpGs.
Then, `rate = 100*Nmet/N`.

FYI These files are created with the following script: https://github.com/rargelaguet/scnmt_gastrulation/blob/master/metacc/annotate/annotate.R

**Comment by yuhanH** [comment]
Thanks for your rapid reply!
